const INITIAL_HANDCARDS_COUNT = 5;
const TOTAL_CARDS_COUNT = 54;
const AUTOMATIC_PASS_TIME = 10;
const SHOW_RESULT_TIME = 5;
const INITIAL_BOUNTY = 10000;
const FEE_PERCENT = 10;

module.exports = {
    INITIAL_HANDCARDS_COUNT,
    TOTAL_CARDS_COUNT,
    AUTOMATIC_PASS_TIME,
    SHOW_RESULT_TIME,
    INITIAL_BOUNTY,
    FEE_PERCENT
}